<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>edgepulse-telemetry-processor</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <!-- Messaging -->
    <PackageReference Include="MailKit" Version="4.9.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />

    <!-- Time-series storage -->
    <PackageReference Include="MongoDB.Driver" Version="3.4.0" />

    <!-- Alert engine: read thresholds + write alerts to SQL Server -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />

    <!-- Serialization -->
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
  </ItemGroup>

</Project>
